In [3]:
%cd stac-mjx
import mediapy as media
import os
from viz import overlay_render
import utils

os.environ["MUJOCO_GL"] = "osmesa"

# set args and initialize params
rat_xml = "../models/rodent_stac_optimized.xml"
data_path = "../adam_exp_tr.p"
params_path = "../params/params.yaml"
calibration_path = "../calibration152529.mat"
video_path = "../Camera2/0.mp4"

n_frames=500
save_path="../videos/overlay_render.mp4"
utils.init_params(params_path)

# call viz and show video
frames = overlay_render(data_path,
                        calibration_path,
                        video_path,
                        rat_xml,
                        n_frames,
                        save_path,
                        camera = "Camera2")
media.show_video(frames, fps=utils.params["RENDER_FPS"])

[Errno 2] No such file or directory: 'stac-mjx'
/home/charles/github/stac-mjx/stac-mjx
rendering frame 0
rendering frame 100
rendering frame 200
rendering frame 300
rendering frame 400
rendering frame 500


In [3]:
import numpy as np

In [4]:
frametimes = np.load("../Camera2/frametimes.npy")
frametimes

array([[1.00000000e+00, 2.00000000e+00, 3.00000000e+00, ...,
        3.59998000e+05, 3.59999000e+05, 3.60000000e+05],
       [0.00000000e+00, 4.12791800e-02, 8.25584000e-02, ...,
        1.48603399e+04, 1.48603811e+04, 1.48604224e+04]])

In [5]:
frametimes.shape

(2, 360000)

In [8]:
frametimes[0][89650:89650 + 100]

array([89651., 89652., 89653., 89654., 89655., 89656., 89657., 89658.,
       89659., 89660., 89661., 89662., 89663., 89664., 89665., 89666.,
       89667., 89668., 89669., 89670., 89671., 89672., 89673., 89674.,
       89675., 89676., 89677., 89678., 89679., 89680., 89681., 89682.,
       89683., 89684., 89685., 89686., 89687., 89688., 89689., 89690.,
       89691., 89692., 89693., 89694., 89695., 89696., 89697., 89698.,
       89699., 89700., 89701., 89702., 89703., 89704., 89705., 89706.,
       89707., 89708., 89709., 89710., 89711., 89712., 89713., 89714.,
       89715., 89716., 89717., 89718., 89719., 89720., 89721., 89722.,
       89723., 89724., 89725., 89726., 89727., 89728., 89729., 89730.,
       89731., 89732., 89733., 89734., 89735., 89736., 89737., 89738.,
       89739., 89740., 89741., 89742., 89743., 89744., 89745., 89746.,
       89747., 89748., 89749., 89750.])

In [9]:
frametimes[1][89650:89650 + 100]

array([3700.66653099, 3700.70781003, 3700.74908908, 3700.79036812,
       3700.83164715, 3700.87292619, 3700.91420523, 3700.95548428,
       3700.99676331, 3701.03804235, 3701.07932139, 3701.12060044,
       3701.16187948, 3701.20315851, 3701.24443754, 3701.28571659,
       3701.32699563, 3701.36827467, 3701.40955371, 3701.45083274,
       3701.49211179, 3701.53339082, 3701.57466987, 3701.6159489 ,
       3701.65722794, 3701.69850698, 3701.73978602, 3701.78106506,
       3701.8223441 , 3701.86362314, 3701.90490218, 3701.94618122,
       3701.98746026, 3702.02873929, 3702.07001833, 3702.11129737,
       3702.15257641, 3702.19385544, 3702.23513448, 3702.2764135 ,
       3702.31769254, 3702.35897158, 3702.40025062, 3702.44152966,
       3702.4828087 , 3702.52408774, 3702.56536678, 3702.60664582,
       3702.64792486, 3702.6892039 , 3702.73048294, 3702.77176198,
       3702.81304101, 3702.85432005, 3702.89559909, 3702.93687813,
       3702.97815717, 3703.01943621, 3703.06071525, 3703.10199

In [10]:
3700.70781003 - 3700.66653099

0.041279040000063105

In [11]:
3700.74908908 - 3700.70781003

0.04127904999995735

In [8]:
import scipy.io as spio
data = spio.loadmat("../save_data_AVG.mat", struct_as_record=False, squeeze_me=True)
data.keys()

dict_keys(['__header__', '__version__', '__globals__', 'pred', 'data', 'p_max', 'sampleID', 'metadata'])

In [19]:
data['pred'].shape

(360000, 3, 23)